version: '3.1'

services:
  joomlaphp:
    image: joomla-custom
    build: .
    ports:
      - 80:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
    volumes:
      - ./src:/var/www/html


  joomladb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql
